import { useState, useEffect, useCallback, useRef } from 'react';
import {
  collection, doc, setDoc, onSnapshot, query,
  where, serverTimestamp,
} from 'firebase/firestore';
import { db } from '../firebase';
import { generateMonthlyInsight, generateWeeklyInsight } from '../services/aiService';
import { isWorkDay, getDaysInMonth } from '../utils/dateUtils';
import type { Employee, AttendanceRecord, NotesRecord, Vacation } from '../types';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface AIInsight {
  id: string;
  type: 'monthly' | 'weekly';
  content: string;
  generatedAt: any;          // Firestore Timestamp | null
  month: number;
  year: number;
  weekNumber?: number;       // 1-5 (week within month)
  weekStart?: number;        // first calendar day of the week
  weekEnd?: number;          // last calendar day of the week
  shift: string;
  isAutoGenerated: boolean;
}

interface UseAIInsightsParams {
  shift: string | null;
  employees: Employee[];
  attendance: AttendanceRecord;
  notes: NotesRecord;
  vacations: Vacation[];
  lockedDays: Record<number, boolean>;
  currentMonth: number;
  currentYear: number;
  validWorkDays: number[];
  isSupervision: boolean;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Return the last work day of the given month/year. */
function getLastWorkDay(month: number, year: number): number {
  const daysInMonth = getDaysInMonth(month, year);
  for (let d = daysInMonth; d >= 1; d--) {
    if (isWorkDay(d, month, year)) return d;
  }
  return daysInMonth;
}

/**
 * Return work days that fall inside a calendar week (Mon-Sun window)
 * defined as: weekStart = (weekNumber - 1) * 7 + 1, weekEnd = min(weekNumber * 7, lastDayOfMonth).
 */
function getWorkDaysForWeek(
  weekNumber: number,
  validWorkDays: number[],
  month: number,
  year: number,
): { days: number[]; start: number; end: number } {
  const daysInMonth = getDaysInMonth(month, year);
  const start = (weekNumber - 1) * 7 + 1;
  const end = Math.min(weekNumber * 7, daysInMonth);
  const days = validWorkDays.filter(d => d >= start && d <= end);
  return { days, start, end };
}

/** Maximum week number that contains at least one day up to `limitDay`. */
function maxWeekNumber(limitDay: number): number {
  return Math.ceil(limitDay / 7);
}

// ─── Hook ─────────────────────────────────────────────────────────────────────

export function useAIInsights({
  shift,
  employees,
  attendance,
  notes,
  vacations,
  lockedDays,
  currentMonth,
  currentYear,
  validWorkDays,
  isSupervision,
}: UseAIInsightsParams) {

  const [monthlyInsight, setMonthlyInsight] = useState<AIInsight | null>(null);
  const [weeklyInsights, setWeeklyInsights] = useState<AIInsight[]>([]);
  const [isGeneratingMonthly, setIsGeneratingMonthly] = useState(false);
  const [isGeneratingWeekly, setIsGeneratingWeekly] = useState<number | null>(null); // week being generated
  const [monthlyError, setMonthlyError] = useState<string | null>(null);
  const [weeklyError, setWeeklyError] = useState<string | null>(null);

  // Guards against firing auto-generation more than once per session/mount.
  const autoMonthlyAttempted = useRef(false);
  const autoWeeklyAttempted  = useRef<Set<number>>(new Set());

  // ─── Firestore Listeners ────────────────────────────────────────────────────

  useEffect(() => {
    if (!shift) return;

    // Monthly insight document
    const monthlyRef = doc(db, 'ai_insights', `monthly_${shift}_${currentYear}_${currentMonth}`);
    const unsubMonthly = onSnapshot(monthlyRef, snap => {
      setMonthlyInsight(snap.exists() ? ({ id: snap.id, ...snap.data() } as AIInsight) : null);
    });

    // All weekly insights for this month/shift
    const weeklyQuery = query(
      collection(db, 'ai_insights'),
      where('shift',  '==', shift),
      where('type',   '==', 'weekly'),
      where('month',  '==', currentMonth),
      where('year',   '==', currentYear),
    );
    const unsubWeekly = onSnapshot(weeklyQuery, snap => {
      const docs: AIInsight[] = [];
      snap.forEach(d => docs.push({ id: d.id, ...d.data() } as AIInsight));
      docs.sort((a, b) => (a.weekNumber ?? 0) - (b.weekNumber ?? 0));
      setWeeklyInsights(docs);
    });

    return () => {
      unsubMonthly();
      unsubWeekly();
    };
  }, [shift, currentMonth, currentYear]);

  // ─── Core: save insight to Firestore ────────────────────────────────────────

  const saveMonthlyInsight = useCallback(async (content: string, isAuto: boolean) => {
    if (!shift) return;
    await setDoc(
      doc(db, 'ai_insights', `monthly_${shift}_${currentYear}_${currentMonth}`),
      {
        type: 'monthly',
        content,
        shift,
        month: currentMonth,
        year: currentYear,
        generatedAt: serverTimestamp(),
        isAutoGenerated: isAuto,
      },
    );
  }, [shift, currentMonth, currentYear]);

  const saveWeeklyInsight = useCallback(async (
    weekNumber: number,
    weekStart: number,
    weekEnd: number,
    content: string,
    isAuto: boolean,
  ) => {
    if (!shift) return;
    await setDoc(
      doc(db, 'ai_insights', `weekly_${shift}_${currentYear}_${currentMonth}_W${weekNumber}`),
      {
        type: 'weekly',
        content,
        shift,
        month: currentMonth,
        year: currentYear,
        weekNumber,
        weekStart,
        weekEnd,
        generatedAt: serverTimestamp(),
        isAutoGenerated: isAuto,
      },
    );
  }, [shift, currentMonth, currentYear]);

  // ─── Generate Monthly ────────────────────────────────────────────────────────

  const triggerMonthlyGeneration = useCallback(async (isAuto: boolean) => {
    if (!shift || isGeneratingMonthly || employees.length === 0) return;
    setIsGeneratingMonthly(true);
    setMonthlyError(null);
    try {
      const content = await generateMonthlyInsight(
        shift,
        currentMonth,
        currentYear,
        employees,
        attendance,
        vacations,
        notes,
        validWorkDays,
      );
      await saveMonthlyInsight(content, isAuto);
    } catch (err: any) {
      setMonthlyError(err?.message || 'Erro ao gerar o insight mensal.');
    } finally {
      setIsGeneratingMonthly(false);
    }
  }, [
    shift, isGeneratingMonthly, employees, currentMonth, currentYear,
    attendance, vacations, notes, validWorkDays, saveMonthlyInsight,
  ]);

  // ─── Generate Weekly ─────────────────────────────────────────────────────────

  const triggerWeeklyGeneration = useCallback(async (weekNumber: number, isAuto: boolean) => {
    if (!shift || isGeneratingWeekly !== null || employees.length === 0) return;
    const { days, start, end } = getWorkDaysForWeek(weekNumber, validWorkDays, currentMonth, currentYear);
    if (days.length === 0) return;

    setIsGeneratingWeekly(weekNumber);
    setWeeklyError(null);
    try {
      const content = await generateWeeklyInsight(
        shift,
        weekNumber,
        start,
        end,
        currentMonth,
        currentYear,
        employees,
        attendance,
        days,
        notes,
      );
      await saveWeeklyInsight(weekNumber, start, end, content, isAuto);
    } catch (err: any) {
      setWeeklyError(err?.message || `Erro ao gerar o insight da semana ${weekNumber}.`);
    } finally {
      setIsGeneratingWeekly(null);
    }
  }, [
    shift, isGeneratingWeekly, employees, currentMonth, currentYear,
    validWorkDays, attendance, notes, saveWeeklyInsight,
  ]);

  // ─── Auto-generation Logic ───────────────────────────────────────────────────
  //
  // Runs whenever `lockedDays` or the Firestore-derived insight state changes.
  // Conditions:
  //   Monthly  → last work day of the month is locked + no insight stored yet
  //   Weekly N → all work days of week N-1 have been passed (we're now in week N
  //              or past end of month) + at least one work day of week N-1 is
  //              locked + no weekly insight for week N-1 stored yet
  //
  useEffect(() => {
    // Only auto-generate for the CURRENT month, not historical ones
    if (!shift || isSupervision || employees.length === 0) return;

    const today      = new Date();
    const isNow      = today.getMonth() === currentMonth && today.getFullYear() === currentYear;
    if (!isNow) return;

    const todayDate  = today.getDate();
    const lastWD     = getLastWorkDay(currentMonth, currentYear);

    // ── Monthly auto-generation ──────────────────────────────────────────────
    const isEndOfMonth        = todayDate >= lastWD;
    const lastWorkDayLocked   = Boolean(lockedDays[lastWD]);
    const noMonthlyInsight    = monthlyInsight === null;

    if (isEndOfMonth && lastWorkDayLocked && noMonthlyInsight && !isGeneratingMonthly && !autoMonthlyAttempted.current) {
      autoMonthlyAttempted.current = true;
      triggerMonthlyGeneration(true);
    }

    // ── Weekly auto-generation ───────────────────────────────────────────────
    // We auto-generate for week W when we're in week W+1 (or later).
    const currentWeek = Math.ceil(todayDate / 7);

    for (let week = 1; week < currentWeek; week++) {
      if (autoWeeklyAttempted.current.has(week)) continue;

      const alreadyExists = weeklyInsights.some(w => w.weekNumber === week);
      if (alreadyExists) {
        autoWeeklyAttempted.current.add(week);
        continue;
      }

      const { days } = getWorkDaysForWeek(week, validWorkDays, currentMonth, currentYear);
      const hasLockedDays = days.some(d => lockedDays[d]);

      if (hasLockedDays && isGeneratingWeekly === null) {
        autoWeeklyAttempted.current.add(week);
        triggerWeeklyGeneration(week, true);
        break; // Generate one at a time to avoid API overload
      }
    }
  }, [
    lockedDays, monthlyInsight, weeklyInsights,
    shift, isSupervision, employees.length,
    currentMonth, currentYear, validWorkDays,
    isGeneratingMonthly, isGeneratingWeekly,
    triggerMonthlyGeneration, triggerWeeklyGeneration,
  ]);

  // Reset session guards when month/year changes
  useEffect(() => {
    autoMonthlyAttempted.current = false;
    autoWeeklyAttempted.current  = new Set();
  }, [currentMonth, currentYear]);

  // ─── Public helpers ──────────────────────────────────────────────────────────

  /** True if the last work day of the month has been locked (list was completed). */
  const canGenerateMonthly = useCallback((): boolean => {
    return Boolean(lockedDays[getLastWorkDay(currentMonth, currentYear)]);
  }, [lockedDays, currentMonth, currentYear]);

  /** True if at least one work day in `weekNumber` has been locked. */
  const canGenerateWeekly = useCallback((weekNumber: number): boolean => {
    const { days } = getWorkDaysForWeek(weekNumber, validWorkDays, currentMonth, currentYear);
    return days.some(d => lockedDays[d]);
  }, [lockedDays, validWorkDays, currentMonth, currentYear]);

  /**
   * Returns week numbers (1-N) that have at least one day that has already
   * occurred (≤ today or ≤ end of the month for historical months).
   */
  const getAvailableWeeks = useCallback((): number[] => {
    const today     = new Date();
    const isNow     = today.getMonth() === currentMonth && today.getFullYear() === currentYear;
    const limitDay  = isNow ? today.getDate() : getDaysInMonth(currentMonth, currentYear);
    const maxWeek   = maxWeekNumber(limitDay);
    return Array.from({ length: maxWeek }, (_, i) => i + 1);
  }, [currentMonth, currentYear]);

  const getWeekRange = useCallback((weekNumber: number) => {
    const { start, end, days } = getWorkDaysForWeek(weekNumber, validWorkDays, currentMonth, currentYear);
    return { start, end, days };
  }, [validWorkDays, currentMonth, currentYear]);

  // ─── Public API ──────────────────────────────────────────────────────────────

  return {
    monthlyInsight,
    weeklyInsights,
    isGeneratingMonthly,
    isGeneratingWeekly,     // null | weekNumber currently being generated
    monthlyError,
    weeklyError,
    setMonthlyError,
    setWeeklyError,
    /** Manually (re-)generate the monthly insight. */
    handleGenerateMonthly: () => triggerMonthlyGeneration(false),
    /** Manually (re-)generate the weekly insight for the given week number. */
    handleGenerateWeekly: (week: number) => triggerWeeklyGeneration(week, false),
    canGenerateMonthly,
    canGenerateWeekly,
    getAvailableWeeks,
    getWeekRange,
    getLastWorkDayOfMonth: () => getLastWorkDay(currentMonth, currentYear),
  };
}