import { useState, useCallback, useMemo, useEffect } from 'react';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { db } from '../firebase'; // 👈 Certifique-se de que o caminho para o firebase.ts está correto
import { generateMonthlyInsight, generateWeeklyInsight } from '../services/aiService';
import { getDaysInMonth, isWorkDay } from '../utils/dateUtils';
import type { Employee, AttendanceRecord, NotesRecord, Vacation } from '../types';

export interface AIInsight {
  content: string;
  generatedAt: string;
  isAutoGenerated: boolean;
  weekNumber?: number;
}

interface UseAIInsightsParams {
  shift: string | null;
  employees: Employee[];
  attendance: AttendanceRecord;
  notes: NotesRecord;
  vacations: Vacation[];
  lockedDays: Record<number, boolean>;
  currentMonth: number;
  currentYear: number;
  validWorkDays: number[];
  isSupervision: boolean;
}

export function useAIInsights({
  shift,
  employees,
  attendance,
  notes,
  vacations,
  lockedDays,
  currentMonth,
  currentYear,
  validWorkDays,
}: UseAIInsightsParams) {
  const [monthlyInsight, setMonthlyInsight] = useState<AIInsight | null>(null);
  const [weeklyInsights, setWeeklyInsights] = useState<AIInsight[]>([]);
  const [isGeneratingMonthly, setIsGeneratingMonthly] = useState(false);
  const [isGeneratingWeekly, setIsGeneratingWeekly] = useState<number | null>(null);
  const [monthlyError, setMonthlyError] = useState<string | null>(null);
  const [weeklyError, setWeeklyError] = useState<string | null>(null);
  const [isLoadingHistory, setIsLoadingHistory] = useState(true);

  const fullMonthWorkDays = useMemo(() => {
    const days: number[] = [];
    const totalDaysInMonth = getDaysInMonth(currentMonth, currentYear);
    for (let d = 1; d <= totalDaysInMonth; d++) {
      if (isWorkDay(d, currentMonth, currentYear)) {
        days.push(d);
      }
    }
    return days;
  }, [currentMonth, currentYear]);

  const getLastWorkDayOfMonth = useCallback(() => {
    return fullMonthWorkDays.length > 0 ? fullMonthWorkDays[fullMonthWorkDays.length - 1] : 31;
  }, [fullMonthWorkDays]);

  const getWeekRange = useCallback((weekNum: number) => {
    const totalDays = fullMonthWorkDays.length;
    const daysPerWeek = Math.ceil(totalDays / 4);
    const startIdx = (weekNum - 1) * daysPerWeek;
    const endIdx = Math.min(weekNum * daysPerWeek, totalDays);
    const weekDays = fullMonthWorkDays.slice(startIdx, endIdx);
    return { start: weekDays[0] || 1, end: weekDays[weekDays.length - 1] || 7, days: weekDays };
  }, [fullMonthWorkDays]);

  // ─── 1. CARREGAR HISTÓRICO DO FIREBASE AO INICIAR (SOBREVIVE AO F5) ───
  useEffect(() => {
    if (!shift) return;

    const fetchInsights = async () => {
      setIsLoadingHistory(true);
      try {
        // Carregar Mensal
        const monthId = `monthly_${shift}_${currentYear}_${currentMonth}`;
        const monthRef = doc(db, 'ai_insights', monthId);
        const monthSnap = await getDoc(monthRef);
        
        if (monthSnap.exists()) {
          setMonthlyInsight(monthSnap.data() as AIInsight);
        } else {
          setMonthlyInsight(null);
        }

        // Carregar Semanais
        const loadedWeeks: AIInsight[] = [];
        for (let w = 1; w <= 4; w++) {
          const weekId = `weekly_${shift}_${currentYear}_${currentMonth}_W${w}`;
          const weekRef = doc(db, 'ai_insights', weekId);
          const weekSnap = await getDoc(weekRef);
          if (weekSnap.exists()) {
            loadedWeeks.push(weekSnap.data() as AIInsight);
          }
        }
        setWeeklyInsights(loadedWeeks.sort((a, b) => (b.weekNumber || 0) - (a.weekNumber || 0)));
      } catch (error) {
        console.error("Erro ao carregar insights do Firebase:", error);
      } finally {
        setIsLoadingHistory(false);
      }
    };

    fetchInsights();
  }, [shift, currentYear, currentMonth]);

  // ─── 2. BLOQUEIOS DE GERAÇÃO (SÓ PERMITE SE NÃO EXISTIR NA BD) ───
  const canGenerateMonthly = useCallback(() => {
    // Só gera se: (1) O último dia está fechado E (2) Ainda NÃO existe um relatório gerado
    return !!lockedDays[getLastWorkDayOfMonth()] && monthlyInsight === null;
  }, [lockedDays, getLastWorkDayOfMonth, monthlyInsight]);

  const canGenerateWeekly = useCallback((weekNum: number) => {
    const { days } = getWeekRange(weekNum);
    if (days.length === 0) return false;
    const lastDayOfWeek = days[days.length - 1];
    
    // Verifica se já existe relatório para esta semana
    const alreadyGenerated = weeklyInsights.some(w => w.weekNumber === weekNum);
    
    // Só gera se o último dia da semana está fechado E não foi gerado ainda
    return !!lockedDays[lastDayOfWeek] && !alreadyGenerated;
  }, [getWeekRange, lockedDays, weeklyInsights]);

  // Payload Builder...
  const buildConsolidatedPayload = (daysToInclude: number[]) => {
    const destaquesPositivos: any[] = [];
    const pontosAtencao: any[] = [];

    employees.forEach(emp => {
      let faltasNoPeriodo = 0;
      const justificativas: string[] = [];

      daysToInclude.forEach(day => {
        const status = attendance[emp.id]?.[day];
        if (status === 'F') {
          faltasNoPeriodo++;
          if (notes[emp.id]?.[day]) {
            justificativas.push(`Dia ${day}: ${notes[emp.id][day]}`);
          }
        }
      });

      if (faltasNoPeriodo === 0) {
        destaquesPositivos.push({ nome: emp.name, cargo: emp.role });
      } else {
        pontosAtencao.push({
          nome: emp.name,
          cargo: emp.role,
          totalFaltas: faltasNoPeriodo,
          justificativas
        });
      }
    });

    return {
      turno: shift,
      totalFuncionarios: employees.length,
      periodo: { inicio: daysToInclude[0], fim: daysToInclude[daysToInclude.length - 1] },
      destaquesPositivos,
      pontosAtencao,
      feriasAtivas: vacations.filter(v => v.status === 'taken').length
    };
  };

  // ─── 3. GERAR E GUARDAR NO FIREBASE ───
  const handleGenerateMonthly = async () => {
    if (!canGenerateMonthly() || !shift) return;
    setIsGeneratingMonthly(true);
    setMonthlyError(null);
    try {
      const payload = buildConsolidatedPayload(validWorkDays);
      const content = await generateMonthlyInsight(payload);
      
      const newInsight: AIInsight = {
        content,
        generatedAt: new Date().toISOString(),
        isAutoGenerated: false
      };

      // Guardar na Base de Dados
      const monthId = `monthly_${shift}_${currentYear}_${currentMonth}`;
      await setDoc(doc(db, 'ai_insights', monthId), newInsight);
      
      setMonthlyInsight(newInsight);
    } catch (err: any) { 
      setMonthlyError(err.message); 
    } finally { 
      setIsGeneratingMonthly(false); 
    }
  };

  const handleGenerateWeekly = async (weekNum: number) => {
    if (!canGenerateWeekly(weekNum) || !shift) return;
    setIsGeneratingWeekly(weekNum);
    setWeeklyError(null);

    try {
      const { days, start, end } = getWeekRange(weekNum);
      const payload = buildConsolidatedPayload(days);

      // ─── BUSCAR CONTEXTO DAS SEMANAS ANTERIORES ───
      // Filtramos apenas as semanas menores que a atual que já possuem conteúdo
      const historyContext = weeklyInsights
        .filter(w => (w.weekNumber || 0) < weekNum)
        .sort((a, b) => (a.weekNumber || 0) - (b.weekNumber || 0))
        .map(w => `RESUMO SEMANA ${w.weekNumber}:\n${w.content}`)
        .join('\n\n---\n\n');

      // Enviamos o historyContext para o serviço de IA
      const content = await generateWeeklyInsight(payload, weekNum, start, end, historyContext);
      
      const newInsight: AIInsight = {
        content,
        generatedAt: new Date().toISOString(),
        isAutoGenerated: false,
        weekNumber: weekNum
      };

      const weekId = `weekly_${shift}_${currentYear}_${currentMonth}_W${weekNum}`;
      await setDoc(doc(db, 'ai_insights', weekId), newInsight);

      setWeeklyInsights(prev => {
        const other = prev.filter(w => w.weekNumber !== weekNum);
        return [...other, newInsight].sort((a, b) => (b.weekNumber || 0) - (a.weekNumber || 0));
      });
    } catch (err: any) { 
      setWeeklyError(err.message); 
    } finally { 
      setIsGeneratingWeekly(null); 
    }
  };

  return {
    monthlyInsight, weeklyInsights, isGeneratingMonthly, isGeneratingWeekly,
    monthlyError, weeklyError, setMonthlyError, setWeeklyError,
    handleGenerateMonthly, handleGenerateWeekly,
    canGenerateMonthly, canGenerateWeekly,
    getAvailableWeeks: () => [1, 2, 3, 4], 
    getWeekRange, 
    getLastWorkDayOfMonth,
    isLoadingHistory // 👈 Adicionado para evitar flashes no ecrã enquanto carrega
  };
}